const SOCKET_URL= "https://fly-eg-staging.fly.dev";
const EXPIRED_MESSAGE="jwt expired";
const ETHAZIUM_DEBUFF=0.6;
const EPIC_WEAKNESS_DEBUFF=0.4;
const ROTTING_PLAGUE_DEBUFF=0.25;
const MARROW_APOCALYPSE_DEBUFF=0.7;

export{
    SOCKET_URL,
    EXPIRED_MESSAGE,
    ETHAZIUM_DEBUFF,
    EPIC_WEAKNESS_DEBUFF,
    ROTTING_PLAGUE_DEBUFF,
    MARROW_APOCALYPSE_DEBUFF
}