export default [{
    "eng": "An instrument of guidance and wonder. Its outer casing, fashioned from shimmering silver, gleams with an otherworldly radiance. Etched upon its surface are intricate sigils and celestial symbols, depicting constellations that seem to shift and align as if choreographed by the heavens themselves. The needle, crafted from a rare crystalline material, hovers within a translucent sphere at the compass's center. It quivers with anticipation, responding not only to magnetic north but also to the mystical currents that flow unseen through the world. When activated, the compass emits a soft, pulsating glow, casting ethereal beams that illuminate the path to the seeker's true destination, be it physical or metaphysical.",
    "esp": "Un instrumento de guía y maravilla. Su estuche exterior, elaborado en un resplandeciente plata, brilla con una luminiscencia de otro mundo. Grabados en su superficie se encuentran sigilos intrincados y símbolos celestiales, que representan constelaciones que parecen moverse y alinearse como si estuvieran coreografiadas por los propios cielos. La aguja, confeccionada a partir de un material cristalino raro, flota dentro de una esfera translúcida en el centro de la brújula. Tiembla con anticipación, respondiendo no solo al norte magnético, sino también a las corrientes místicas que fluyen invisiblemente a través del mundo. Cuando se activa, la brújula emite un suave resplandor pulsante, proyectando haces etéreos que iluminan el camino hacia el verdadero destino del buscador, ya sea físico o metafísico."
},
{
    "eng": "Within its hollowed eye sockets, faint glimmers of iridescent energy pulse intermittently, hinting at the dormant power encapsulated within. Runes and symbols of forgotten languages adorn the crown of the skull, glowing softly with an ethereal luminescence that ebbs and flows like the tides of an arcane ocean.",
    "esp": "Dentro de sus cuencas oculares huecas, destellos tenues de energía iridiscente pulsan intermitentemente, insinuando el poder latente encapsulado en su interior. Runas y símbolos de lenguajes olvidados adornan la corona del cráneo, brillando suavemente con una luminiscencia etérea que fluye y refluye como las mareas de un océano arcano."
},
{
    "eng": "A sanctum of arcane communion. Hewn from ancient oak, the table bears ornate carvings that depict the intertwining of mystical creatures and esoteric symbols. Runes, aglow with a faint luminescence, encircle the table's perimeter, pulsating in rhythm with the ebb and flow of the surrounding magic. At the center rests a focal point—a crystalline prism, refracting ambient light into a myriad of spectral hues. Upon this prism, etchings of forgotten languages spiral outward, intertwining with celestial motifs that seem to stir and shimmer as if infused with a cosmic breath. Candles, aligned at precise intervals, burn with a steady, ethereal flame, casting dancing shadows that amplify the mystical ambiance. When invoked, the table resonates with a subtle vibration, harmonizing with the intentions of the adept, serving as a conduit between the realms of the mundane and the transcendental.",
    "esp": "Un santuario de comunión arcana. Labrada en roble antiguo, la mesa lleva tallados ornamentales que representan la interacción de criaturas místicas y símbolos esotéricos. Runas, resplandecientes con una tenue luminiscencia, rodean el perímetro de la mesa, palpitando al compás del vaivén de la magia circundante. En el centro reposa un punto focal: un prisma cristalino que refracta la luz ambiental en una miríada de tonos espectrales. Sobre este prisma, grabados de lenguajes olvidados se espiralan hacia afuera, entrelazándose con motivos celestiales que parecen agitarse y brillar como si estuvieran impregnados con un aliento cósmico. Velas, alineadas en intervalos precisos, arden con una llama etérea y constante, proyectando sombras danzantes que amplifican la atmósfera mística. Cuando se invoca, la mesa resuena con una vibración sutil, armonizando con las intenciones del adepto y sirviendo como un conducto entre los reinos de lo mundano y lo trascendental."
},
{
    "eng": "Crafted from sturdy steel, its surface bears the scars of countless conflicts, each mark a testament to the valor and resilience of its former bearer. The edges, though worn, retain a faint glint of silver amidst the patina of age. Emblazoned upon its face is a crest, depicting a soaring eagle with outstretched wings—a symbol of courage and freedom frozen in time. The center of the shield holds a deep indentation, a remnant of a formidable blow that the hero valiantly withstood in the heat of a pivotal battle. Though tarnished by the passage of time, the shield still emanates an aura of strength and protection, a silent tribute to the bravery of the hero who once bore it into the fray, defending against adversaries and safeguarding allies.",
    "esp": "Un escudo, desgastado por el tiempo y las batallas, alguna vez empuñado con orgullo por un héroe caído. Forjado en acero resistente, su superficie lleva las cicatrices de innumerables conflictos, cada marca testamento del valor y la resistencia de su antiguo portador. Los bordes, aunque desgastados, conservan un leve destello plateado en medio de la pátina del tiempo. En su faz está emblematizado un escudo, mostrando un águila majestuosa con alas extendidas, un símbolo de coraje y libertad congelado en el tiempo. El centro del escudo muestra una hendidura profunda, un vestigio de un golpe formidable que el héroe resistió valientemente en el fragor de una batalla crucial. Aunque manchado por el paso del tiempo, el escudo aún emana un aura de fuerza y protección, un tributo silencioso a la valentía del héroe que alguna vez lo llevó al fragor de la batalla, defendiendo contra adversarios y protegiendo a sus aliados."
}]